apiVersion: v2
name: adot-container-insights
description: AWS Distro for OpenTelemetry Collector for Container Insights on EKS Fargate
version: 0.1.0
appVersion: "latest"
keywords:
  - aws
  - otel
  - opentelemetry
  - container-insights
  - cloudwatch
  - fargate
  - eks
