apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.resourceNames.deploymentName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.resourceNames.appLabel }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.resourceNames.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.resourceNames.appLabel }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8888"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Values.resourceNames.containerName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config=/conf/config.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /conf
          ports:
            - containerPort: 8888
              name: metrics
              protocol: TCP
            - containerPort: 13133
              name: health
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ .Values.resourceNames.configMapName }}
